### ISSUE TITLE
Remove the gem_plugin dependency ?

### ISSUE THREAD

**Issue by zimbatm** [evan/mongrel#16]
Is anyone using that feature of mongrel ? Is it really necessary ?

**Comment by luislavena** [comment]
mongrel_cluster and mongrel_service depend on it right now.

If gem_plugin is removed, an alternative mechanism to load the plugins is required.

Patches are welcome.

**Comment by zimbatm** [comment]
Thanks,

Closing the ticket because I see no solution that's easy and would not break things.

mongrel + all the plugins would need to be patched at the same time, mongrel would need to include a similar mechanism, versions would need a major bump and there is risks of breaks. For the sake of removing a dependency. I can live with it :)
