### ISSUE TITLE
syntax error on ruby 1.9.2-p0

### ISSUE THREAD

**Issue by dimaspriyanto** [evan/mongrel#20]
I tried to run sinatra and got the following mongrel errors on ruby version 1.9.2-p0.
Fyi. it's working on ruby version 1.8.7
- Dimas

/home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel/handlers.rb:214: warning: else without rescue is useless
internal:lib/rubygems/custom_require:29:in `require': /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel/handlers.rb:208: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
...te(modified_since) rescue nil : false
...                               ^
/home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel/handlers.rb:209: syntax error, unexpected ':', expecting keyword_end
...                              : false
...                               ^
/home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel/handlers.rb:210: syntax error, unexpected ':', expecting keyword_end
...                              : false
...                               ^
/home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel/handlers.rb:211: syntax error, unexpected ':', expecting keyword_end
...                              : false
...                               ^
/home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel/handlers.rb:212: syntax error, unexpected ':', expecting keyword_end
...).include?(etag)              : false
...                               ^
/home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel/handlers.rb:468: syntax error, unexpected keyword_end, expecting $end
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/mongrel-1.1.5/lib/mongrel.rb:22:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:33:in`require'
    from internal:lib/rubygems/custom_require:33:in `rescue in require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/handler/mongrel.rb:1:in `<top (required)>'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/handler.rb:17:in`const_get'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/handler.rb:17:in `block in get'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/handler.rb:17:in`each'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/handler.rb:17:in `get'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.1.3/lib/sinatra/base.rb:1181:in`block in detect_rack_handler'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.1.3/lib/sinatra/base.rb:1179:in `each'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.1.3/lib/sinatra/base.rb:1179:in`detect_rack_handler'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.1.3/lib/sinatra/base.rb:1140:in `run!'
    from /home/dimas/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.1.3/lib/sinatra/main.rb:25:in`block in module:Sinatra'

**Comment by evan** [comment]
Try mongrel -v 1.2.0.pre2 (available in Rubygems).
