### ISSUE TITLE
Unable to compile gem on Windows

### ISSUE THREAD

**Issue by coding-red-panda** [evan/mongrel#25]
When I try to install the gem using rubygems it works without problems. I receive problems however when I download the source from github and try to run setup.rb

This is the output from the command:

C:\Source\git\mongrel>setup.rb
---> bin
<--- bin
---> lib
---> lib/mongrel
<--- lib/mongrel
<--- lib
---> ext
---> ext/http11
C:/Ruby/bin/ruby.exe C:/Source/git/mongrel/ext/http11/extconf.rb
checking for main() in -lc... no
creating Makefile
---> ext/http11/org
---> ext/http11/org/jruby
---> ext/http11/org/jruby/mongrel
<--- ext/http11/org/jruby/mongrel
<--- ext/http11/org/jruby
<--- ext/http11/org
<--- ext/http11
<--- ext
---> bin
<--- bin
---> lib
---> lib/mongrel
<--- lib/mongrel
<--- lib
---> ext
---> ext/http11
make
make: **\* Er is geen regel om doel '/C/Ruby/include/ruby-1.9.1/ruby.h' te maken,
 nodig voor 'http11.o'.  Gestopt.
C:/Source/git/mongrel/setup.rb:655:in `command': system("make") failed (RuntimeE
rror)
        from C:/Source/git/mongrel/setup.rb:664:in`make'
        from C:/Source/git/mongrel/setup.rb:1258:in `setup_dir_ext'
        from C:/Source/git/mongrel/setup.rb:1532:in`block in traverse'
        from C:/Source/git/mongrel/setup.rb:1549:in `dive_into'
        from C:/Source/git/mongrel/setup.rb:1530:in`traverse'
        from C:/Source/git/mongrel/setup.rb:1534:in `block (2 levels) in travers
e'
        from C:/Source/git/mongrel/setup.rb:1533:in`each'
        from C:/Source/git/mongrel/setup.rb:1533:in `block in traverse'
        from C:/Source/git/mongrel/setup.rb:1549:in`dive_into'
        from C:/Source/git/mongrel/setup.rb:1530:in `traverse'
        from C:/Source/git/mongrel/setup.rb:1524:in`block in exec_task_traverse
'
        from C:/Source/git/mongrel/setup.rb:1519:in `each'
        from C:/Source/git/mongrel/setup.rb:1519:in`exec_task_traverse'
        from C:/Source/git/mongrel/setup.rb:1246:in `exec_setup'
        from C:/Source/git/mongrel/setup.rb:996:in`exec_setup'
        from C:/Source/git/mongrel/setup.rb:813:in `invoke'
        from C:/Source/git/mongrel/setup.rb:773:in`invoke'
        from C:/Source/git/mongrel/setup.rb:1578:in `<main>'

**Comment by luislavena** [comment]
Hello,

Dunno what is your toolchain/version of Ruby or if you're using RubyInstaller + the DevKit or not.

So will be a shoot in the dark, did you see this page:

https://github.com/oneclick/rubyinstaller/wiki/Troubleshooting#ruby_h

**Comment by coding-red-panda** [comment]
I have the DevKit installed for ruby, as well as a complete msys/minGW toolchain for compiling native C/C++ extensions for the Ruby on Rails gems.

I can run following commands from the commandline without trouble : make, gcc, g++
So the toolchain is properly configured. I will look a bit further, as I have a feeling it's related to the paths beeing generated with make in Windows.

**Comment by luislavena** [comment]
Please note that `setup.rb` will install into Ruby site_ruby directory.

Have you tried the following?
- Open a new command prompt
- Invoke devkitvars from the DevKit installation
- cd into mongrel source code
- do `rake compile`

Please let me know the results of that.

**Comment by luislavena** [comment]
BTW, there is a pre-release version of mongrel that is already compiled for Ruby 1.8 and 1.9

**Comment by coding-red-panda** [comment]
The issue appeared to be a path conflict in Windows.
Sorted it now and compiles like a charm.
