### ISSUE TITLE
Mongrel 1.2 with mongrel_service 0.4

### ISSUE THREAD

**Issue by adamdennis** [evan/mongrel#4]
I installed mongrel-1.2.0.pre2-mingw32.gem.
However I can now not install mongrel_service-0.4.beta3 as it requires mongrel-1.1.5.

Should I wait until mongrel 1.2 is finalised?

Thanks.

**Comment by luislavena** [comment]
Mongrel 1.2 will be released this week, along mongrel_service final.

Will keep this Issue open until that is completed.

Thank you.

**Comment by natebird** [comment]
Any word on new releases for mongrel 1.2 and mongrel_service 0.4?

**Comment by luislavena** [comment]
mongrel_service 0.4.0 was released yesterday:

http://groups.google.com/group/rubyinstaller/browse_thread/thread/9328a231e5e08d69

You can now use mongrel 1.1.5 or mongrel 1.2.0

**Comment by natebird** [comment]
Great! Congratulations… thank you for your work on this project.

**Comment by adamdennis** [comment]
Thanks Luis - great work as ever.
