### ISSUE TITLE
mongrel.rubyforge.com link broken

### ISSUE THREAD

**Issue by ghost** [evan/mongrel#6]
Just a heads-up... the link to mongrel.rubyforge.com on your frontpage just goes to rubyforge.com

**Comment by luislavena** [comment]
Closing, there is no rubyforge.com. is rubyforge.org:

http://mongrel.rubyforge.org redirects properly.

Closing this out.

**Comment by smtlaissezfaire** [comment]
Maybe it should be changed on github:

http://screencast.com/t/NGQyZTI0O
