### ISSUE TITLE
Unable to start mongrel with ruby 1.9.1 in Windows Server 2008 (64 bit)

### ISSUE THREAD

**Issue by nimli** [evan/mongrel#7]
Running "mongrel_rails start" shows a pop-up window:

"The program can't start because mscvrt-ruby18.dll is missing from your computer.  Try reinstalling the program to fix this problem."

The server cannot start.

Running "gem list --local" shows:

...
mongrel (1.1.5)
...
rails (2.3.5)
...

and "ruby -v" shows:

"ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-mingw32]"

In another computer, which runs Windows XP (32 bit), I have:

"ruby 1.8.7 (2010-01-10 patchlevel 249) [i386-mingw32]"

and I have no problem to start the mongrel server.

Is there a problem to run mongrel with ruby 1.9?
If so, will the problem be fixed soon?  Thank you.

**Comment by luislavena** [comment]
Mongrel 1.1.5 is not compatible with Ruby 1.9, you need either compile yourself (force ruby platform during gem installation) or use prerelease version.

Known issue already solved.

**Comment by nimli** [comment]
Thank you for your reply.  

If I understand correctly, there is no plan to make Mongrel to become compatible with Ruby 1.9, and the workaround is to "force ruby platform during gem installation" for Ruby 1.9 or any newer release of Ruby.

Can you tell me where I can find instructions or steps to implement the workaround?  Many thanks!

**Comment by luislavena** [comment]
No, there is, mongrel 1.2.0 prerelease is compatible with Ruby 1.9.1

The current 1.1.5 binaries are not compatible, you cannot mix binaries between 1.8 and 1.9.

http://rubygems.org/gems/mongrel/versions/1.2.0.pre2

**Comment by nimli** [comment]
Great!  Thank you!!  I hope the GA release of 1.2.0 will be available soon.  :-)
