### ISSUE TITLE
Mongrel requires dispatcher which has been removed from Rails 3

### ISSUE THREAD

**Issue by calamitas** [evan/mongrel#9]
When I try running Mongrel with Rails 3, this works OK until I try to daemonize the server, i.e., rails s -d dies before it can serve any requests.

When I use mongrel_cluster, the processes also die. The log files give this error:
/Users/peter/.rvm/gems/ruby-1.9.2-preview3@rails3beta/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require': no such file to load -- dispatcher (LoadError)

I'm using Rails 3 RC and Ruby 1.9.2 preview3. The error is caused by Rails because dispatcher is removed from Rails 3. Thin has the same problem; for more details, look here: https://rails.lighthouseapp.com/projects/8994/tickets/3980-rails-3-not-working-with-thin . Note that the quick fix mentioned there (require "rails/dispatcher") no longer works with Rails 3 RC.

**Comment by luislavena** [comment]
This is also related to GH-2

**Comment by Bochenski** [comment]
Same thing happens when using mongrel_rails start

**Comment by luislavena** [comment]
Closing this as is related to Issue #2
